[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ai = { workspace = true }
async-trait = { workspace = true }
plugins = { workspace = true }
ormlite = { version = "0.24.5", default-features = false, features = ["runtime-tokio-rustls", "default-sqlite", "time", "uuid", "json"] }
open = "5"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
thiserror = { workspace = true }
tokio = { workspace = true }
tool = { workspace = true }
uuid = { workspace = true }
